### ISSUE TITLE
Fatal Error on PM 4.16.0

### ISSUE THREAD

**Issue by MrDeadPool86** [Laith98Dev/PluginManager#1]
Fatal error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of Laith98Dev\PluginManager\libs\Vecnavium\FormsUI\Form::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar://D:/Minecraft Server/PocketMine-MP/plugins/PluginManager.phar/src/Laith98Dev/PluginManager/libs/Vecnavium/FormsUI/Form.php:53
Stack trace:
#0 phar://D:/Minecraft Server/PocketMine-MP/plugins/PluginManager.phar/src/Laith98Dev/PluginManager/libs/Vecnavium/FormsUI/Form.php(10): pocketmine\errorhandler\ErrorToExceptionHandler::handle(8192, 'Return type of ...', 'phar://D:/Minec...', 53)
#1 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(93): include('phar://D:/Minec...')
#2 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(83): BaseClassLoader->loadClass('Laith98Dev\\Plug...')
#3 phar://D:/Minecraft Server/PocketMine-MP/plugins/PluginManager.phar/src/Laith98Dev/PluginManager/libs/Vecnavium/FormsUI/SimpleForm.php(7): BaseClassLoader->{closure}('Laith98Dev\\Plug...')
#4 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(93): include('phar://D:/Minec...')
#5 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/vendor/pocketmine/classloader/src/BaseClassLoader.php(83): BaseClassLoader->loadClass('Laith98Dev\\Plug...')
#6 phar://D:/Minecraft Server/PocketMine-MP/plugins/PluginManager.phar/src/Laith98Dev/PluginManager/Main.php(59): BaseClassLoader->{closure}('Laith98Dev\\Plug...')
#7 phar://D:/Minecraft Server/PocketMine-MP/plugins/PluginManager.phar/src/Laith98Dev/PluginManager/commands/PluginCommand.php(65): Laith98Dev\PluginManager\Main->OpenMainForm(Object(pocketmine\player\Player))
#8 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/command/SimpleCommandMap.php(205): Laith98Dev\PluginManager\commands\PluginCommand->execute(Object(pocketmine\player\Player), 'plugin', Array)
#9 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/Server.php(1441): pocketmine\command\SimpleCommandMap->dispatch(Object(pocketmine\player\Player), 'plugin')
#10 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/player/Player.php(1451): pocketmine\Server->dispatchCommand(Object(pocketmine\player\Player), 'plugin')
#11 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/network/mcpe/handler/InGamePacketHandler.php(739): pocketmine\player\Player->chat('/plugin')
#12 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket.php(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(Object(pocketmine\network\mcpe\protocol\CommandRequestPacket))
#13 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/network/mcpe/NetworkSession.php(458): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(Object(pocketmine\network\mcpe\handler\InGamePacketHandler))
#14 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/network/mcpe/NetworkSession.php(411): pocketmine\network\mcpe\NetworkSession->handleDataPacket(Object(pocketmine\network\mcpe\protocol\CommandRequestPacket), 'M\x07/plugin\x00-O#8\x04...')
#15 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/network/mcpe/raklib/RakLibInterface.php(189): pocketmine\network\mcpe\NetworkSession->handleEncoded('\x93\xF5e\xD7/\xC8)M\xCF\xCCc\xD0\xF5W\xB6...')
#16 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver.php(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(0, '\xFE\xDAO!"\xE6\xCEY\x87\xDA\xBA\xA42\r\xDC...')
#17 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/network/mcpe/raklib/RakLibInterface.php(116): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(Object(pocketmine\network\mcpe\raklib\RakLibInterface))
#18 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/vendor/pocketmine/snooze/src/SleeperHandler.php(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#19 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/TimeTrackingSleeperHandler.php(58): pocketmine\snooze\SleeperHandler->processNotifications()
#20 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/vendor/pocketmine/snooze/src/SleeperHandler.php(82): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#21 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/Server.php(1700): pocketmine\snooze\SleeperHandler->sleepUntil(1678634976.4369)
#22 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/Server.php(1056): pocketmine\Server->tickProcessor()
#23 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/PocketMine.php(339): pocketmine\Server->__construct(Object(BaseClassLoader), Object(pocketmine\utils\MainLogger), 'D:\\Minecraft Se...', 'D:\\Minecraft Se...')
#24 phar://D:/Minecraft Server/PocketMine-MP/PocketMine-MP.phar/src/PocketMine.php(362): pocketmine\server()
#25 D:\Minecraft Server\PocketMine-MP\PocketMine-MP.phar(11): require('phar://D:/Minec...')
#26 {main} in phar://D:/Minecraft Server/PocketMine-MP/plugins/PluginManager.phar/src/Laith98Dev/PluginManager/libs/Vecnavium/FormsUI/Form.php on line 10

**Comment by Laith98Dev** [comment]
FormsUI issue... awaiting next update

**Comment by Laith98Dev** [comment]
I've try and it works fine, are u sure that you're using latest commit?
